### PATIENT DETAILS
GET http://localhost:1234/

### ADMIT

POST http://localhost:1234/admit
Content-Type: application/json

{
    "patientId": 3030,
    "patientName": "Gopi",
    "age": 33,
    "bloodGroup": "A+",
    "address": "Attur",
    "contact": 92335649595,
    "issue": "Cancer",
    "status": "Discharged"
}


###

### FILTER

GET http://localhost:1234/filter/patientName/Gopi


### UPDATE

PUT http://localhost:1234/update/Cancer/Admit

###

DELETE http://localhost:1234/erase/668e5b33ff058e177a1844ac

### DELETE

DELETE http://localhost:1234/discharge/Gopi

###

### DELETE BY AGE 

DELETE http://localhost:1234/ageRemove/30

###

### DELETE BY STATUS

DELETE http://localhost:1234/statusRemove/Admit

###