### PATIENT DETAILS
GET http://localhost:1234/hospital

### ADMIT

POST http://localhost:1234/hospital/admit
Content-Type: application/json

{
    "patientId": 7070,
    "patientName": "Gopi",
    "age": 33,
    "bloodGroup": "AB+",
    "address": "Chennai",
    "contact": 91211447495,
    "issue": "Tummor",
    "status": "Admit"
}


###

### Updateusing ID

PUT  http://localhost:1234/hospital/
Content-Type: application/json

{
    "_id":"6695f8777b3faf47dc9a705b",
    "patientId": 8080,
    "patientName": "Gopi",
    "age": 33,
    "bloodGroup": "AB+",
    "address": "Chennai",
    "contact": 91211447495,
    "issue": "Tummor",
    "status": "Admit"
}


###

### FILTER

GET http://localhost:1234/hospital/filter/patientName/Gopi

###

GET http://localhost:1234/hospital/6695f8777b3faf47dc9a705b


### UPDATE

PUT http://localhost:1234/hospital/update/Cancer/Admit

###


### DELETE

DELETE http://localhost:1234/hospital/discharge/Gopi

###

### DELETE WITH ID

DELETE http://localhost:1234/hospital/delete/66936c1ac8b811225e3f7177

###

### DELETE BY AGE 

DELETE http://localhost:1234/hospital/ageRemove/30

###

### DELETE BY STATUS

DELETE http://localhost:1234/hospital/statusRemove/Admit

###

